name: Update README - Recent Activity

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update recent activity
        uses: jamesgeorge007/github-activity-readme@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'chore: update README with latest activity'
